### ISSUE TITLE
Possibly include a black/dark background for dark theme

### ISSUE THREAD

**Issue by tyBouch** [CryoliteZ/MaTerialgram#1]
I use a really large window, and the centered aspect of telegram means that the white background is causing me no end to issues with eye strain. Could you set the background color of the extra space to a darker color?

**Comment by alvinbhou** [comment]
I have updated the extension to version 1.0.4, the extra space of the dark theme should now been set to a dark color. I think this is a great idea and makes the theme more consistent. If there are any problems, feel free to reopen the issue.

**Comment by tyBouch** [comment]
I just saw and actually tested it out. It looks a ton better, and is much
easier on the eyes!
Should something happen regarding it I'll let you know. I use Opera, so my
updates will be slightly delayed, though. (Have to manually install chrome
extensions)
