### ISSUE TITLE
Layout is broken when horizontal viewport is large

### ISSUE THREAD

**Issue by immutable-pro** [CryoliteZ/MaTerialgram#2]
Hello,

The layout of the site breaks when the horizontal viewport is large.

The screenshot is taken on a 2015 Macbook Pro 13". Making the horizontal size of the window smaller fixes it. 

Thanks!
![Screenshot_2019-08-28 Telegram Web](https://user-images.githubusercontent.com/44724765/63848022-ed90c800-c986-11e9-8526-f6143cefcf7e.png)

**Comment by alvinbhou** [comment]
Hello,
I tested the extension on XPS13 (13.3")  with 3200x1800, 2560x1600, 1920x1080 resolutions and different window sizes. However, I could not reproduce the result. Can you provide the viewport/window size (width and height) and the resolution of your laptop where the site breaks? 

Thanks for supporting this project!

**Comment by immutable-pro** [comment]
Sure,

Just tried on Firefox 70, it breaks at 1610x1343 (external monitor, 3440x1440, Firefox Window size 1610x1390).

On my Macbook Pro 13" I can't reproduce it consistently. However, on my external monitor, it happens all the time.

**Comment by alvinbhou** [comment]
I tried some testing with my desktop but I still couldn't reproduce the issue. I'll continue investigate about this issue if I get a larger and higher resolution monitor.

**Comment by liamcooper** [comment]
Hi,
I'm also having this issue on my 4k monitor. 

If there is no conversation selected then the layout is correct:
![1](https://user-images.githubusercontent.com/7249112/91034900-a5d66800-e5fd-11ea-8792-8b6412196f6d.png)

When a conversation is selected then the messages show to the right hand side of the page:
![2](https://user-images.githubusercontent.com/7249112/91034949-b981ce80-e5fd-11ea-9fc0-1833c4b7c31b.png)

If I add the style `clear:both` to the element with class `im_page_wrap`, then the layout is correct:
![3](https://user-images.githubusercontent.com/7249112/91035176-17161b00-e5fe-11ea-95da-23723c577804.png)

Hope this helps.

**Comment by alvinbhou** [comment]
Thanks @liamcooper! I have added your fix and published a new version. It may take a while for the Chrome store to update, let me know if the issues persist.

Also, @immutable-pro hope this fixes your problem after the new update. This issue has been hanging here for quite a while...
